[#87] Landing Page Api 만들기
mimi-teams/Meezle-Backend pull request #88
Opened 2023-01-18 15:39 UTC by YeongRoYun

# 🙊 Issues

resolved #87 

# 🤠 작업 내용

Landing Page 에 현재 이벤트 및 이용자 수를 반환하는 Api 생성
TTL 1 로 Cache 적용(EHCache 3)

2023-01-18 15:44 UTC, YeongRoYun commented on src/main/java/com/mimi/w2m/backend/config/interceptor/LoginCheckHandler.java
> +//    private final UserService userService;
여기에서 userService 를 사용하면, UserService 에 EnhancerBySpringCGLIB 의 Proxy 가 적용되지 않습니당(EHCache Proxy) 왜 그런건가요? 그래서 Cache 가 적용되지 않는 문제가 있었습니당
# 재현
1. 주석 풀기
2. LandingApi 의 의 Get Method 에 Break point 걸고, Debug
3. GET /landing 날리기
4. Intellij 를 보면, UserService 만 EnhancerBySpringCGLIB 가 안붙어있음

2023-01-18 15:44 UTC, YeongRoYun commented on src/test/java/com/mimi/w2m/backend/service/UserServiceTest.java
> +    void testCache() {
Cache 가 정상적으로 동작하는지 테스트하고 싶은데, 어떤 형식으로 진행해야 할까요?

2023-01-18 15:44 UTC, YeongRoYun commented on src/test/java/com/mimi/w2m/backend/W2mApplicationTest.java
>  class W2mApplicationTest {
Cache 를 적용 후, 모든 테스트를 돌릴 때, Named Cache 가 중복으로 생성되어 테스트가 실패합니다. 어떻게 고칠 수 있나용?

2023-01-19 06:08 UTC, Yeh35 requested changes

2023-01-19 06:08 UTC, Yeh35 commented on src/main/java/com/mimi/w2m/backend/config/interceptor/LoginCheckHandler.java
> +//    private final UserService userService;
엇 이건 확인해볼께요

2023-01-19 06:08 UTC, Yeh35 commented on src/test/java/com/mimi/w2m/backend/W2mApplicationTest.java
>  class W2mApplicationTest {
엇 이것도 확인해볼꼐요

2023-01-19 06:08 UTC, Yeh35 commented on src/test/java/com/mimi/w2m/backend/service/UserServiceTest.java
> +    void testCache() {
https://www.baeldung.com/spring-data-testing-cacheable
CacheManager를 통해서 캐시가 적용되었는지 확인할 수 있습니다.

2023-01-19 09:55 UTC, YeongRoYun commented on src/test/java/com/mimi/w2m/backend/service/UserServiceTest.java
> +    void testCache() {
감사합니당 ㅎㅎ

2023-01-19 09:56 UTC, YeongRoYun commented on build.gradle
> +//}
풀어도 각 테스트에 적용되지 않고, 그냥 개별 테스트마다 @ActiveProfiles("test") 로 적용하기로 했습니당

2023-01-19 09:56 UTC, YeongRoYun commented on src/main/java/com/mimi/w2m/backend/api/v1/LandingApi.java
> +        final var numUsers = userService.getTotal();
넵

2023-01-22 10:17 UTC, Yeh35 approved these changes

2023-02-02 09:37 UTC, merged